repos:
  # Essential code quality checks - informative only
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        verbose: true
        args: [--check-only]
      - id: end-of-file-fixer
        verbose: true
      - id: check-yaml
        verbose: true
      - id: check-toml
        verbose: true
      - id: debug-statements
        language_version: python3

  # Linting - check only mode
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: [--no-fix, --show-fixes]
        stages: [pre-commit]
        fail_fast: false
      - id: ruff-format
        args: [--check]
        stages: [pre-commit]
        fail_fast: false

  # Security checks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.3.0
    hooks:
      - id: detect-secrets
        exclude: "package-lock.json|poetry.lock"
        stages: [pre-commit]
        fail_fast: false

  # Simple branch protection
  - repo: local
    hooks:
      - id: protected-branch-check
        name: Protected Branch Warning
        entry: |
          #!/bin/bash
          branch=$(git rev-parse --abbrev-ref HEAD)
          if [[ $branch =~ ^(main|master|develop|production|staging)$ ]]; then
              echo "⚠️  Warning: You're on protected branch: $branch"
              exit 1
          fi
          exit 0
        language: system
        stages: [pre-push]
        verbose: true