repos:
  # Essential code quality checks - informative only
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        verbose: true
        files: ^(main\.py|run_tests\.py|tools/.+\.py)$
      - id: end-of-file-fixer
        verbose: true
        args: []
        files: ^(main\.py|run_tests\.py|tools/.+\.py)$
      - id: check-yaml
        verbose: true
        files: ^(\.pre-commit-config\.yaml|railway\.yaml)$
      - id: check-toml
        verbose: true
        files: ^(pyproject\.toml)$
      - id: debug-statements
        language_version: python3
        files: ^(main\.py|run_tests\.py|tools/.+\.py)$

  # Linting - check only mode
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: [--no-fix, --show-fixes]
        files: ^(main\.py|run_tests\.py|tools/.+\.py)$
        stages: [pre-commit]
        fail_fast: false
      - id: ruff-format
        files: ^(main\.py|run_tests\.py|tools/.+\.py)$
        stages: [pre-commit]

  # Security checks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.3.0
    hooks:
      - id: detect-secrets
        # Only check main deployment files and tools
        files: ^(main\.py|run_tests\.py|tools/.+\.py)$
        exclude: "package-lock.json|poetry.lock"
        stages: [pre-commit]
        fail_fast: false

  # Simple branch protection
  - repo: local
    hooks:
      - id: protected-branch-check
        name: Protected Branch Warning
        entry: |
          #!/bin/bash
          branch=$(git rev-parse --abbrev-ref HEAD)
          if [[ $branch =~ ^(main|master|develop|production|staging)$ ]]; then
              echo "⚠️  Warning: You're on protected branch: $branch"
              exit 1
          fi
          exit 0
        language: system
        stages: [pre-push]
        verbose: true
      - id: prevent-merge-commits
        name: Block merge commits
        entry: |
          #!/bin/bash
          if git log --merges -n 1 --pretty=%H HEAD^..HEAD | grep -q .; then
            echo "❌ Merge commits prohibited! Use rebase instead."
            exit 1
          fi
        language: system
        stages: [commit-msg]
        verbose: true