name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Ruff linting
      run: |
        # Only check main deployment files and tools
        ruff check "main.py" "run_tests.py" "tools/" --no-fix --show-fixes
        ruff format "main.py" "run_tests.py" "tools/" --check

    - name: Check for secrets
      run: |
        # Only scan crucial files
        detect-secrets scan main.py run_tests.py tools/

    - name: Run tests
      run: |
        # Only if tests directory exists
        if [ -d "tests" ]; then
          pytest tests/
        else
          echo "No tests directory found, skipping tests"
          exit 0
        fi

    - name: Type checking
      run: |
        # Only check main deployment files and tools
        mypy main.py run_tests.py tools/ --ignore-missing-imports