name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install pre-commit ruff pytest detect-secrets

    - name: Run pre-commit checks
      run: |
        pre-commit run --all-files --show-diff-on-failure

    - name: Run Ruff linting
      run: |
        ruff check . --no-fix --show-fixes
        ruff format . --check

    - name: Check for secrets
      run: detect-secrets scan

    - name: Run tests
      run: |
        cd tests
        pytest .